### ISSUE TITLE
No file was found when using first_found

### ISSUE THREAD

**Issue by AndrewSav** [andrewrothstein/ansible-packer#5]
Play:

```
---
- hosts: localhost
  gather_facts: no
  vars:
  roles:
    - andrewrothstein.packer
```

Error:
```
No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found
```

Apparently `gather_facts` is mandatory, but it is not easy to see and it's not documented.
